airbot_lidar_2:
  ros__parameters:
    port: "/dev/sc_mini2"
    frame_id: "base_scan_back"
    ignore_array: ""
    baudrate: 230400
    samp_rate: 9
    resolution_fixed: true
    singleChannel: false
    auto_reconnect: true
    reversion: true
    isToFLidar: false
    angle_max: 360.0
    angle_min: 0.0
    max_range: 12.0
    min_range: 0.1
    frequency: 10.0
    angle_increment: 0.1
    version: 4
