NORMAL:
  controller_server:
    ros__parameters:
      general_goal_checker:
        xy_goal_tolerance: 0.15
        yaw_goal_tolerance: 6.28 
      FollowPath:
        plugin: "nav2_rotation_shim_controller::RotationShimController"
        angular_dist_threshold: 0.3
        forward_sampling_distance: 0.5
        rotate_to_heading_angular_vel: 0.3
        max_angular_accel: 1.0
        min_speed_xy: 0.0
        min_vel_x: 0.0
        max_vel_x: 0.2
        min_speed_theta: 0.0
        max_vel_theta: 0.3
        max_speed_xy: 0.2
        acc_lim_x: 1.6
        acc_lim_theta: 1.0 
        decel_lim_x: -1.6
        decel_lim_theta: -1.0 
        xy_goal_tolerance: 0.05
        sim_time: 3.0
  # velocity_smoother:
  #   ros__parameters:
  #     max_velocity: [0.3, 0.0, 0.4]
  #     min_velocity: [-0.3, 0.0, -0.4]
  #     max_accel: [1.0, 0.0, 2.0]
  #     max_decel: [-1.0, 0.0, -2.0]
  local_costmap:
    local_costmap:
      ros__parameters:
        inflation_layer:
          enabled: True
        voxel_layer:
          enabled: True 
        static_layer:
          enabled: True 
        obstacle_layer:
          enabled: True
  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          enabled: True 
        static_layer:
          enabled: True 
        inflation_layer:
          enabled: True 
DOCK:
  controller_server:
    ros__parameters:
      general_goal_checker:
        xy_goal_tolerance: 0.2 #0.15
        yaw_goal_tolerance: 0.02
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        angular_dist_threshold: 0.3
        forward_sampling_distance: 0.5
        rotate_to_heading_angular_vel: 0.3
        max_angular_accel: 0.5
        min_speed_xy: 0.0
        min_vel_x: 0.0
        max_vel_x: 0.1
        min_speed_theta: 0.0
        max_vel_theta: 0.2
        max_speed_xy: 0.1
        acc_lim_x: 1.0
        acc_lim_theta: 1.5
        decel_lim_x: -1.0
        decel_lim_theta: -1.5
        xy_goal_tolerance: 0.05
        sim_time: 3.0
  # velocity_smoother:
  #   ros__parameters:
  #     max_velocity: [0.3, 0.0, 0.4]
  #     min_velocity: [-0.3, 0.0, -0.4]
  #     max_accel: [1.0, 0.0, 2.0]
  #     max_decel: [-1.0, 0.0, -2.0]
  local_costmap:
    local_costmap:
      ros__parameters:
        inflation_layer:
          enabled: True  # Changed from orignial
        voxel_layer:
          enabled: True # Changed from orignial
        static_layer:
          enabled: True ## Changed from orignial
        obstacle_layer:
          enabled: True
  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          enabled: True # Changed from orignial
        static_layer:
          enabled: True # Changed from orignial
        inflation_layer:
          enabled: True # Changed from orignial
AUTO:
  controller_server:
    ros__parameters:
      general_goal_checker:
        xy_goal_tolerance: 0.2
        yaw_goal_tolerance: 0.02
      FollowPath:
        plugin: "nav2_rotation_shim_controller::RotationShimController"
        angular_dist_threshold: 0.3
        forward_sampling_distance: 1.0
        rotate_to_heading_angular_vel: 0.25
        max_angular_accel: 1.0
        min_speed_xy: 0.0
        min_vel_x: 0.0
        max_vel_x: 0.3
        min_speed_theta: 0.0
        max_vel_theta: 0.25
        max_speed_xy: 0.25
        acc_lim_x: 1.0
        acc_lim_theta: 1.0 
        decel_lim_x: -1.0
        decel_lim_theta: -1.0
        xy_goal_tolerance: 0.05
        sim_time: 3.0
  # velocity_smoother:
  #   ros__parameters:
  #     max_velocity: [0.3, 0.0, 0.4]
  #     min_velocity: [-0.3, 0.0, -0.4]
  #     max_accel: [1.0, 0.0, 2.0]
  #     max_decel: [-1.0, 0.0, -2.0]
  local_costmap:
    local_costmap:
      ros__parameters:
        inflation_layer:
          enabled: True  # Changed from orignial
        voxel_layer:
          enabled: True # Changed from orignial
        static_layer:
          enabled: True ## Changed from orignial
        obstacle_layer:
          enabled: True
  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          enabled: True # Changed from orignial
        static_layer:
          enabled: True # Changed from orignial
        inflation_layer:
          enabled: True # Changed from orignial
# 전진 빠져나오기
CHARGE_UNDOCK: 
  controller_server:
    ros__parameters:
      general_goal_checker:
        xy_goal_tolerance: 0.2
        yaw_goal_tolerance: 0.05 # 회전 필요 X
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        angular_dist_threshold: 6.28
        forward_sampling_distance: 0.5
        rotate_to_heading_angular_vel: 0.0
        max_angular_accel: 1.0
        min_speed_xy: 0.0 # Little Back
        min_vel_x: 0.0 # Little Back
        max_vel_x: 0.1
        min_speed_theta: 0.0
        max_vel_theta: 0.3 # Little rotation
        max_speed_xy: 0.1
        acc_lim_x: 1.5
        acc_lim_theta: 2.0
        decel_lim_x: -1.5
        decel_lim_theta: -2.0
        xy_goal_tolerance: 0.05
  local_costmap:
    local_costmap:
      ros__parameters:
        inflation_layer:
          enabled: True  # Changed from orignial
        voxel_layer:
          enabled: True # Changed from orignial
        static_layer:
          enabled: True ## Changed from orignial
        obstacle_layer:
          enabled: True
  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          enabled: True # Changed from orignial
        static_layer:
          enabled: True # Changed from orignial
        inflation_layer:
          enabled: True # Changed from orignial
# 후진 빠져나오기 -> costmap layer를 없애는 것 대신 scan의 범위를 조절할 것!
MANIPULATION_UNDOCK: 
  controller_server:
    ros__parameters:
      general_goal_checker:
        xy_goal_tolerance: 0.2
        yaw_goal_tolerance: 0.05 # 앞 방향 보존
      FollowPath:
        plugin: "nav2_rotation_shim_controller::RotationShimController"
        angular_dist_threshold: 6.28
        forward_sampling_distance: 0.5
        rotate_to_heading_angular_vel: 0.0
        max_angular_accel: 0.3
        min_speed_xy: -0.02 # Little Back
        min_vel_x: -0.02 # Little Back
        max_vel_x: 0.1
        min_speed_theta: 0.0
        max_vel_theta: 0.2 # Little rotation
        max_speed_xy: 0.05
        acc_lim_x: 1.5
        acc_lim_theta: 0.3
        decel_lim_x: -1.5
        decel_lim_theta: -0.5
        xy_goal_tolerance: 0.05
        sim_time: 3.0
  # velocity_smoother:
  #   ros__parameters:
  #     max_velocity: [0.0, 0.0, 0.02] 
  #     min_velocity: [-0.05, 0.0, -0.02] 
  #     max_accel: [0.5, 0.0, 0.1]
  #     max_decel: [-0.5, 0.0, -0.1] 
  local_costmap:
    local_costmap:
      ros__parameters:
        inflation_layer:
          enabled: True  # Changed from orignial
        voxel_layer:
          enabled: True # Changed from orignial
        static_layer:
          enabled: True ## Changed from orignial
        obstacle_layer:
          enabled: True
  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          enabled: True # Changed from orignial
        static_layer:
          enabled: True # Changed from orignial
        inflation_layer:
          enabled: True # Changed from orignial
# Charging 상태에서 Redocking 할 때, 전진+회전 빠져나오기
CHARGE_REDOCK: 
  controller_server:
    ros__parameters:
      general_goal_checker:
        xy_goal_tolerance: 0.2
        yaw_goal_tolerance: 0.02
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        angular_dist_threshold: 6.28
        forward_sampling_distance: 0.5
        rotate_to_heading_angular_vel: 0.0
        max_angular_accel: 1.0
        min_speed_xy: 0.0 # Little Back
        min_vel_x: 0.0 # Little Back
        max_vel_x: 0.1
        min_speed_theta: 0.0
        max_vel_theta: 0.3 # Little rotation
        max_speed_xy: 0.1
        acc_lim_x: 1.5
        acc_lim_theta: 2.0
        decel_lim_x: -1.5
        decel_lim_theta: -2.0
        xy_goal_tolerance: 0.05

  # velocity_smoother:
  #   ros__parameters:
  #     max_velocity: [0.05, 0.0, 0.02] 
  #     min_velocity: [0.0, 0.0, -0.02] 
  #     max_accel: [0.5, 0.0, 0.1]
  #     max_decel: [-0.5, 0.0, -0.1] 
  local_costmap:
    local_costmap:
      ros__parameters:
        inflation_layer:
          enabled: True  
        voxel_layer:
          enabled: True 
        static_layer:
          enabled: True 
        obstacle_layer:
          enabled: True
  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          enabled: True 
        static_layer:
          enabled: True 
        inflation_layer:
          enabled: True 
# Manipulation 에서 Redocking 할 때, 후진+회전 빠져나오기
MANIPULATION_REDOCK: 
  controller_server:
    ros__parameters:
      general_goal_checker:
        xy_goal_tolerance: 0.2
        yaw_goal_tolerance: 0.02 # 앞 방향 보존
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        angular_dist_threshold: 6.28
        forward_sampling_distance: 0.5
        rotate_to_heading_angular_vel: 0.0
        max_angular_accel: 0.2
        min_speed_xy: -0.05
        min_vel_x: -0.05
        max_vel_x: 0.02 # Little Straight
        min_speed_theta: 0.0
        max_vel_theta: 0.05 # Little rotation
        max_speed_xy: 0.02 # Little Straight
        acc_lim_x: 1.5
        acc_lim_theta: 0.3
        decel_lim_x: -1.5
        decel_lim_theta: -0.5
        xy_goal_tolerance: 0.3
  # velocity_smoother:
  #   ros__parameters:
  #     max_velocity: [0.0, 0.0, 0.02] 
  #     min_velocity: [-0.05, 0.0, -0.02] 
  #     max_accel: [0.5, 0.0, 0.1]
  #     max_decel: [-0.5, 0.0, -0.1] 
  local_costmap:
    local_costmap:
      ros__parameters:
        inflation_layer:
          enabled: True 
        voxel_layer:
          enabled: True
        static_layer:
          enabled: True 
        obstacle_layer:
          enabled: True
  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          enabled: True 
        static_layer:
          enabled: True 
        inflation_layer:
          enabled: True
# NORMAL:
#   controller_server:
#     ros__parameters:
#       general_goal_checker:
#         xy_goal_tolerance: 0.05
#         yaw_goal_tolerance: 0.02
#       FollowPath:
#         desired_linear_vel: 0.3
#         max_approach_linear_velocity: 0.2
#         min_approach_linear_velocity: 0.05 
#         allow_reversing: false
#   local_costmap:
#     local_costmap:
#       ros__parameters:
#         inflation_layer:
#           enabled: True
#         voxel_layer:
#           enabled: True 
#         static_layer:
#           enabled: True 
#         obstacle_layer:
#           enabled: True
#   global_costmap:
#     global_costmap:
#       ros__parameters:
#         obstacle_layer:
#           enabled: True 
#         static_layer:
#           enabled: True 
#         inflation_layer:
#           enabled: True 
# DOCK:
#   controller_server:
#     ros__parameters:
#       general_goal_checker:
#         xy_goal_tolerance: 0.1
#         yaw_goal_tolerance: 0.02
#       FollowPath:
#         desired_linear_vel: 0.3
#         max_approach_linear_velocity: 0.2 
#         min_approach_linear_velocity: 0.05
#         use_rotate_to_heading: true
#         allow_reversing: false

# AUTO:
#   controller_server:
#     ros__parameters:
#       general_goal_checker:
#         xy_goal_tolerance: 0.1
#         yaw_goal_tolerance: 0.02
#       FollowPath:
#         desired_linear_vel: 0.3
#         max_approach_linear_velocity: 0.2
#         min_approach_linear_velocity: 0.05
#         use_rotate_to_heading: true
#         allow_reversing: false

# # 전진 빠져나오기
# CHARGE_UNDOCK: 
#   controller_server:
#     ros__parameters:
#       general_goal_checker:
#         xy_goal_tolerance: 0.07
#         yaw_goal_tolerance: 0.02
#       FollowPath:
#         desired_linear_vel: 0.05
#         max_approach_linear_velocity: 0.05 
#         min_approach_linear_velocity: 0.02
#         use_rotate_to_heading: false
#         allow_reversing: false
#   local_costmap:
#     local_costmap:
#       ros__parameters:
#         inflation_layer:
#           enabled: True  # Changed from orignial
#         voxel_layer:
#           enabled: True # Changed from orignial
#         static_layer:
#           enabled: True ## Changed from orignial
#         obstacle_layer:
#           enabled: True
#   global_costmap:
#     global_costmap:
#       ros__parameters:
#         obstacle_layer:
#           enabled: True # Changed from orignial
#         static_layer:
#           enabled: True # Changed from orignial
#         inflation_layer:
#           enabled: True # Changed from orignial
# # 후진 빠져나오기 -> costmap layer를 없애는 것 대신 scan의 범위를 조절할 것!
# MANIPULATION_UNDOCK: 
#   controller_server:
#     ros__parameters:
#       general_goal_checker:
#         xy_goal_tolerance: 0.05
#         yaw_goal_tolerance: 0.05 # 앞 방향 보존
#       FollowPath:
#         plugin: "nav2_rotation_shim_controller::RotationShimController"
#         angular_dist_threshold: 6.28
#         forward_sampling_distance: 0.5
#         rotate_to_heading_angular_vel: 0.0
#         max_angular_accel: 0.3
#         min_speed_xy: -0.02 # Little Back
#         min_vel_x: -0.02 # Little Back
#         max_vel_x: 0.1
#         min_speed_theta: 0.0
#         max_vel_theta: 0.2 # Little rotation
#         max_speed_xy: 0.05
#         acc_lim_x: 0.01
#         acc_lim_theta: 0.3
#         decel_lim_x: -0.01
#         decel_lim_theta: -0.5
#         xy_goal_tolerance: 0.05
#         sim_time: 3.0
#   # velocity_smoother:
#   #   ros__parameters:
#   #     max_velocity: [0.0, 0.0, 0.02] 
#   #     min_velocity: [-0.05, 0.0, -0.02] 
#   #     max_accel: [0.5, 0.0, 0.1]
#   #     max_decel: [-0.5, 0.0, -0.1] 
#   local_costmap:
#     local_costmap:
#       ros__parameters:
#         inflation_layer:
#           enabled: True  # Changed from orignial
#         voxel_layer:
#           enabled: True # Changed from orignial
#         static_layer:
#           enabled: True ## Changed from orignial
#         obstacle_layer:
#           enabled: True
#   global_costmap:
#     global_costmap:
#       ros__parameters:
#         obstacle_layer:
#           enabled: True # Changed from orignial
#         static_layer:
#           enabled: True # Changed from orignial
#         inflation_layer:
#           enabled: True # Changed from orignial
# # Charging 상태에서 Redocking 할 때, 전진+회전 빠져나오기
# CHARGE_REDOCK: 
#   controller_server:
#     ros__parameters:
#       general_goal_checker:
#         xy_goal_tolerance: 0.07
#         yaw_goal_tolerance: 0.02
#       FollowPath:
#         desired_linear_vel: 0.1
#         max_approach_linear_velocity: 0.1 
#         min_approach_linear_velocity: 0.02
#         use_rotate_to_heading: false
#         allow_reversing: false
#   local_costmap:
#     local_costmap:
#       ros__parameters:
#         inflation_layer:
#           enabled: True  # Changed from orignial
#         voxel_layer:
#           enabled: True # Changed from orignial
#         static_layer:
#           enabled: True ## Changed from orignial
#         obstacle_layer:
#           enabled: True
#   global_costmap:
#     global_costmap:
#       ros__parameters:
#         obstacle_layer:
#           enabled: True # Changed from orignial
#         static_layer:
#           enabled: True # Changed from orignial
#         inflation_layer:
#           enabled: True # Changed from orignial

# # Manipulation 에서 Redocking 할 때, 후진+회전 빠져나오기
# MANIPULATION_REDOCK: 
#   controller_server:
#     ros__parameters:
#       general_goal_checker:
#         xy_goal_tolerance: 0.05
#         yaw_goal_tolerance: 0.02 # 앞 방향 보존
#       FollowPath:
#         plugin: "dwb_core::DWBLocalPlanner"
#         angular_dist_threshold: 6.28
#         forward_sampling_distance: 0.5
#         rotate_to_heading_angular_vel: 0.0
#         max_angular_accel: 0.2
#         min_speed_xy: -0.05
#         min_vel_x: -0.05
#         max_vel_x: 0.02 # Little Straight
#         min_speed_theta: 0.0
#         max_vel_theta: 0.05 # Little rotation
#         max_speed_xy: 0.02 # Little Straight
#         acc_lim_x: 0.01
#         acc_lim_theta: 0.3
#         decel_lim_x: -0.01
#         decel_lim_theta: -0.5
#         xy_goal_tolerance: 0.3
#   # velocity_smoother:
#   #   ros__parameters:
#   #     max_velocity: [0.0, 0.0, 0.02] 
#   #     min_velocity: [-0.05, 0.0, -0.02] 
#   #     max_accel: [0.5, 0.0, 0.1]
#   #     max_decel: [-0.5, 0.0, -0.1] 
#   local_costmap:
#     local_costmap:
#       ros__parameters:
#         inflation_layer:
#           enabled: True 
#         voxel_layer:
#           enabled: True
#         static_layer:
#           enabled: True 
#         obstacle_layer:
#           enabled: True
#   global_costmap:
#     global_costmap:
#       ros__parameters:
#         obstacle_layer:
#           enabled: True 
#         static_layer:
#           enabled: True 
#         inflation_layer:
#           enabled: True