version: "1.0.0"
manufacturer: "Inc.CASELAB"
serialNumber: "AMMR20_001"

typeSpecification:
  seriesName: "AMMR20_001"
  agvKinematic: "DIFF"
  agvClass: "CARRIER"
  maxLoadMass: 20.0
  localizationTypes:
    - "NATURAL"
  navigationTypes:
    - "AUTONOMOUS"