simulationMode: false
currentMapNode:
  currentMapID: geumjeong_show
  currentNodeID: geumjeong_show
  currentMap: geumjeong_show
  currentNode: geumjeong_show_node
  # currentNode: caselab_demoroom_test_node