/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera_l_optical_link"
      pixel_format: "mjpeg2rgb"
      av_device_format: "YUV422P"
      image_width: 640
      image_height: 480
      camera_name: "camera_left"
      # Using separate camera calibration for left camera
      camera_info_url: "package://usb_cam/config/camera_info_left.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 60
      # autofocus: false  # Not supported by this camera
      # focus: -1         # Not supported by this camera