interface_node:
  ros__parameters:

    # For interface
    odom_timeout: 3.0
    battery_low_threshold: 30.0
    battery_charged_threshold: 80.0

    # For Docking Client
    charging_marker_gap: 0.25
    working_marker_gap: 0.25
    marker_id: 1

execution_node:
  ros__parameters:

    # For Last GoalDistance Threshold (m)
    goal_distance_threshold: 1.0

    # For Charging Timeout (seconds)
    charging_timout: 60.0 
    charging_relay_timeout: 60.0 # 60.0

    filtered_scan_topic: filtered_scan

    # For Obstacle Detect Distance Threshold (m)
    obstacle_distance_threshold: 1.8
    dynamic_threshold: 0.2
    min_cluster_size: 3

    # For USS Distance Threshold (mm)
    uss_threshold: 100