scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: BracketBoundsFilter1
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 2.87
        upper_angle: 3.141592

    filter2:
      name: BracketBoundsFilter2
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -3.141592
        upper_angle: -2.87

    filter3:
      name: ProfileBoundsFilter1
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 2.5
        upper_angle: 2.87

    filter4:
      name: ProfileBoundsFilter2
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -2.87
        upper_angle: -2.5
