scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: polygon_filter
      type: laser_filters/LaserScanPolygonFilter
      params:
        polygon_frame: base_footprint
        polygon: '[[-0.40, -0.33], [-0.40, 0.33], [0.40, 0.33], [0.40, -0.33]]'
        invert: false
        footprint_topic: base_footprint_exclude
